#!/bin/sh /etc/rc.common
# 
# start watchdog
#
# https://openwrt.org/docs/guide-developer/procd-init-script-example
# Copyright (C) 2020 luani.de

# Init sequence
START=99
STOP=10

# PROCD
USE_PROCD=1

start_service() {
	procd_open_instance watchping
	procd_set_param command /bin/sh "/usr/lib/watchping/watchping.sh"

	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

	procd_set_param stdout 1 # forward stdout of the command to logd
	procd_set_param stderr 1 # same for stderr

	procd_set_param pidfile /var/run/watchping.pid

	procd_close_instance
}

stop_service() {
	logger -t "watchping" "watchdog stopped!"
}

service_triggers()
{
	procd_add_reload_trigger "watchping"
}

reload_service()
{
	stop
	start
}
